blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'


urlpatterns = [
    path("", views.post_list, name='post_list'),
    path("<int:id>/", views.post_detail, name='post_detail'),
    path("post/share/", views.PostShareView.as_view(), name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:id>/post/delete/', views.post_delete, name='delete'),
    path('search/', views.post_search, name='post_search'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from blog.sitemaps import PostSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {"posts":PostSitemap}



urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap' )
]

blog/models.py
from django.db import models
from taggit.managers import TaggableManager
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User



class Post(models.Model):
         STATUS_CHOICES = (
         ('draft', 'Draft'),
         ('published', 'Published'),
         )
         title = models.CharField(max_length=250)
         slug = models.SlugField(max_length=250,
                                     unique_for_date='publish')
         author = models.ForeignKey(User,
                                     on_delete=models.CASCADE,
                                     related_name='blog_posts')
         body = models.TextField()
         publish = models.DateTimeField(default=timezone.now)
         created = models.DateTimeField(auto_now_add=True)
         updated = models.DateTimeField(auto_now=True)
         status = models.CharField(max_length=10,
                                     choices=STATUS_CHOICES,
                                     default='draft')
         tags = TaggableManager()

         class Meta:
            ordering = ('-publish',)
         def __str__(self):
                return self.title

         def get_absolute_url(self):
             return reverse('blog:post_detail',
                            args=[self.publish.year,
                                  self.publish.month,
                                  self.publish.day, self.slug])






class Comment(models.Model):
         post = models.ForeignKey(Post,
         on_delete=models.CASCADE,
         related_name='comments')
         name = models.CharField(max_length=80)
         email = models.EmailField()
         body = models.TextField()
         created = models.DateTimeField(auto_now_add=True)
         updated = models.DateTimeField(auto_now=True)
         active = models.BooleanField(default=True)
         class Meta:
                ordering = ('created',)
         def __str__(self):
             return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms

from blog.models import Comment, Post


class SharePostForm(forms.ModelForm):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
     class Meta:
         model = Comment
         fields = ('name', 'email', 'body')



class SearchForm(forms.Form):
        query = forms.CharField()

blog/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View

from taggit.models import Tag

from .forms import SharePostForm, CommentForm,SearchForm
from .models import Post, Comment

from django.contrib.postgres.search import SearchVector,SearchRank,SearchQuery,TrigramSimilarity


def post_list(request, tag_slug = None):
    form = SearchForm()
    query = None
    result = []
    object_list = Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug = tag_slug)
        object_list = object_list.filter(tags__in = [tag])
    pagination = Paginator(object_list, 2)
    page_num = request.GET.get('page',1)
    posts = pagination.get_page(page_num)
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            result = Post.objects.annotate(
                search = SearchVector('title', 'body',),
            ).filter(search=query)


    return render(request,
                  'blog/post_list.html',
                  {'posts': posts,
                   'tag':tag,
                   'form':form,
                   'results':result,
                   'query':query}
                  )

def post_detail(request, id):
         post = Post.objects.get(id=id)
         form = CommentForm()
         comments = post.comments.all()
         if request.method == 'POST':
             form = CommentForm(request.POST)
             if form.is_valid():
                 Comment.objects.create(
                      post = post,
                      name = request.POST['name'],
                      body = request.POST['body'],
                      email = request.POST['email']

                 )
                 return redirect(reverse("blog:post_detail", kwargs={'id': post.id}))
         post_tags_ids = post.tags.values_list('id', flat=True)
         similar_posts = Post.objects.filter(tags__in = post_tags_ids).exclude(id=id)
         similar_posts = similar_posts.annotate(same_tags = Count('tags')).order_by('-same_tags', 'publish')

         return render(request,
                             'blog/post_detail.html',
                             {'post': post,
                              'form':form,
                              'comments':comments,
                              'similar_posts':similar_posts})

def post_delete(request, id):
    post = Post.objects.get(id=id)
    post.delete()
    return redirect('blog:post_list')



class PostShareView(View):
    def get(self,request):
       return render(request,'blog/post_share.html')
    def post(self, request):
        message = request.POST['message']
        name = request.POST['name']
        email = request.POST['email']
        send_mail(
            'Jamshid',
            message ,
            'settings.EMAIL_HOST_USER',
            [email],fail_silently=False
        )

        return render(request, 'blog/post_share.html')


def post_search(request):
    form = SearchForm()
    query = None
    result = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            result = Post.objects.annotate(
                similarity = TrigramSimilarity('title', query),
            ).filter(similarity__gt = 0.1
            ).order_by('-similarity')
    return render(request, 'blog/post_search.html', {"form":form, "query":query, "results":result})

blog/templates/blog/latest_posts.html
<ul>
 {% for post in latest_posts %}
 <li>
 <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
 </li>
 {% endfor %}
</ul>

blog/templates/blog/post_delete.html
{% extends 'base.html' %}


{% block content %}

Delete this post

<button>Yes delete</button>


{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block content %}
<div class="row mt-5">
    <div class="col">
                <h1>{{ post.title }}</h1>
             <p class="date">
             Published {{ post.publish }} by {{ post.author }}
             </p>
             {{ post.body }}
            <a href="{% url 'blog:post_share' %}">Share this post</a>

            <h2>Similar posts</h2>
            {% for post in similar_posts %}
             <p>
             <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
             </p>
            {% empty %}
             There are no similar posts yet.
            {% endfor %}
            <a href="{% url 'blog:delete' post.id %}" class="btn btn-warning">Delete this post</a>
    </div>

    <div class="col">
        <h2>Add Comment</h2>

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-primary mb-5">Save comment</button>
            </form>

    </div>
    <div class="col">
            <b>{{ comments.count }} comment</b>

            <h2>Comments</h2>
            {% for comment in comments %}
                     <p>
                        <b>{{ comment.name }}</b>

                    </p>
                    <p>
                        <span>Created at - {{ comment.created }}</span>
                    </p>
                    <p>
                        {{ comment.body|markdown }}
                    </p>
            {% endfor %}

    </div>
</div>







{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load blog_tags %}


{% block content %}


<!--<form method="get">-->
<!--    {% csrf_token %}-->
<!--    {{ form.as_p }}-->
<!--    <button>Search</button>-->
<!--</form>-->
<!--{% with results.count as total_count %}-->
<!--<p><b>Found {{ total_count }} posts</b></p>-->
<!--{% endwith %}-->
<!--{% for post in results %}-->

<!--<h3>-->
<!--    <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>-->

<!--</h3>-->

<!--{% endfor %}-->

<!--<br><hr>-->
 {% for post in posts %}
          <h2>
          <a href="{% url 'blog:post_detail' post.id %}" >
          {{ post.title }}
          </a>
          </h2>
     {% if post.tags %}
              <p class="tags">
                     Tags:
                     {% for tag in post.tags.all %}
                     <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                     {{ tag.name }}
                     </a>
                     {% if not forloop.last %}, {% endif %}
                     {% endfor %}
              </p>
     {% endif %}
           <p class="date">
           Published {{ post.publish }} by {{ post.author }}
           </p>
           {{ post.body|markdown|truncatewords_html:30 }}
 {% endfor %}


 {% if posts.has_previous %}
  <a href="?page={{ posts.previous_page_number }}"><< Previous</a>
 {% endif %}
  {% if posts.has_next %}
 <a href="?page={{ posts.next_page_number }}">Next >></a>
 {% endif %}

{% endblock %}

blog/templates/blog/post_search.html
{% extends 'base.html' %}


{% block content %}

 {% if query %}
 <h1>Posts containing "{{ query }}"</h1>
 <h3>
 {% with results.count as total_results %}
 Found {{ total_results }} result{{ total_results|pluralize }}
 {% endwith %}
 </h3>
 {% for post in results %}
 <h4><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h4>
 {{ post.body }}
 {% empty %}
 <p>There are no results for your query.</p>
 {% endfor %}
 <p><a href="{% url "blog:post_search" %}">Search again</a></p>
 {% else %}
 <h1>Search for posts</h1>
 <form method="get">
 {{ form.as_p }}
  <a href="{% url 'blog:post_list' %}" class="btn btn-info">Post list</a>
 <input class="btn btn-success" type="submit" value="Search">
 </form>
 {% endif %}
{% endblock %}

blog/templates/blog/post_share.html
{% extends 'base.html' %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <input name="name" placeholder="Name" type="text" required>
    <br><br>
    <input name="email" placeholder="E-mail" type="email" required>
    <br><br>
    <textarea name="message" placeholder="Message"  required></textarea>
    <br><br>
    <button>
        Send E-Mail
    </button>
    <br><br>

</form>

{% endblock %}

templates/base.html
{% load blog_tags %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django-2</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body class="bg-light">
<div class="row">
    <div class="col-sm-8">
        <h1 style="text-align:center;">My blog</h1><hr>
        {% block content %}
        {% endblock %}
    </div>
    <div class="col-md-4 ms-auto">
        <div style="background-color:Gainsboro">
        <h3 style="text-align:center;">This is my blog . I've written {% total_posts %} posts so far.</h3>
        <h4>Latest posts</h4>
        {% show_latest_posts 3 %}
        <h5>
               The most total Commented post
        </h5>
            {% get_most_commented_posts as most_commented_posts %}
        <ul>
            {% for post in most_commented_posts %}
            <li>
                <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
            </li>
            {% endfor %}
        </ul>
        <a href="{% url 'blog:post_search' %}" class="btn btn-primary">Search Post</a>

        </div>

    </div>

</div>


</body>
</html>